// <auto-generated />
using System;
using EngineeringSoftwareLicensingTracker.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EngineeringSoftwareLicensingTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719192716_LicensesV2")]
    partial class LicensesV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EngineeringSoftwareLicensingTracker.Entities.Activities.ActivityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WorkerEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkerEntityId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("EngineeringSoftwareLicensingTracker.Entities.LicenseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastUsedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SlotsOccupied")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSlots")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("EngineeringSoftwareLicensingTracker.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LicenseEntityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("WorkerEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LicenseEntityId");

                    b.HasIndex("WorkerEntityId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("EngineeringSoftwareLicensingTracker.Entities.WorkerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("EngineeringSoftwareLicensingTracker.Entities.WorkplaceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WorkerEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkerEntityId");

                    b.ToTable("Workplaces");
                });

            modelBuilder.Entity("EngineeringSoftwareLicensingTracker.Entities.Activities.ActivityEntity", b =>
                {
                    b.HasOne("EngineeringSoftwareLicensingTracker.Entities.WorkerEntity", "WorkerEntity")
                        .WithMany()
                        .HasForeignKey("WorkerEntityId");

                    b.Navigation("WorkerEntity");
                });

            modelBuilder.Entity("EngineeringSoftwareLicensingTracker.Entities.Reservation", b =>
                {
                    b.HasOne("EngineeringSoftwareLicensingTracker.Entities.LicenseEntity", null)
                        .WithMany("Reservations")
                        .HasForeignKey("LicenseEntityId");

                    b.HasOne("EngineeringSoftwareLicensingTracker.Entities.WorkerEntity", "WorkerEntity")
                        .WithMany("Reservations")
                        .HasForeignKey("WorkerEntityId");

                    b.Navigation("WorkerEntity");
                });

            modelBuilder.Entity("EngineeringSoftwareLicensingTracker.Entities.WorkplaceEntity", b =>
                {
                    b.HasOne("EngineeringSoftwareLicensingTracker.Entities.WorkerEntity", "WorkerEntity")
                        .WithMany()
                        .HasForeignKey("WorkerEntityId");

                    b.Navigation("WorkerEntity");
                });

            modelBuilder.Entity("EngineeringSoftwareLicensingTracker.Entities.LicenseEntity", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("EngineeringSoftwareLicensingTracker.Entities.WorkerEntity", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
